### ISSUE TITLE
Indicator Script Error

### ISSUE THREAD

**Issue by mburakergenc** [bettimms/multi-gekko#2]
I'm getting the following error when I try to analyze pairs on Binance. 

`npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multi-gekko@1.0.0 BTS-RSI.bin: `node /Users/akyayik/code/gekko/gekko.js --config /Users/akyayik/code/multi-gekko/configs/BTS/BTS-RSI.bin.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the multi-gekko@1.0.0 BTS-RSI.bin script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by bettimms** [comment]
It's really hard to know from this description what's wrong with it but try removing them all and generate again or even go track in the npm logs what's wrong with it.

**Comment by mburakergenc** [comment]
Here is my debug info. I think it fails at the run all script. I did run a fresh install of Gekko and Multi Gekko btw. 

`
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/9.3.0_1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'run-all' ]
2 info using npm@5.6.0
3 info using node@v9.3.0
4 verbose run-script [ 'prerun-all', 'run-all', 'postrun-all' ]
5 info lifecycle multi-gekko@1.0.0~prerun-all: multi-gekko@1.0.0
6 info lifecycle multi-gekko@1.0.0~run-all: multi-gekko@1.0.0
7 verbose lifecycle multi-gekko@1.0.0~run-all: unsafe-perm in lifecycle true
8 verbose lifecycle multi-gekko@1.0.0~run-all: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/akyayik/code/gekko-trial/multi-gekko/node_modules/.bin:/Users/akyayik/.rbenv/shims:/Users/akyayik/google-cloud-sdk/bin:/Users/akyayik/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/010 Editor.app/Contents/CmdLine
9 verbose lifecycle multi-gekko@1.0.0~run-all: CWD: /Users/akyayik/code/gekko-trial/multi-gekko
10 silly lifecycle multi-gekko@1.0.0~run-all: Args: [ '-c',
10 silly lifecycle   'npm-run-all --parallel BCH-MACD.gda ETH-MACD.gda ADA-RSI.bin BCH-RSI.gda ETH-RSI.bin' ]
11 silly lifecycle multi-gekko@1.0.0~run-all: Returned: code: 1  signal: null
12 info lifecycle multi-gekko@1.0.0~run-all: Failed to exec run-all script
13 verbose stack Error: multi-gekko@1.0.0 run-all: `npm-run-all --parallel BCH-MACD.gda ETH-MACD.gda ADA-RSI.bin BCH-RSI.gda ETH-RSI.bin`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:159:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:159:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid multi-gekko@1.0.0
15 verbose cwd /Users/akyayik/code/gekko-trial/multi-gekko
16 verbose Darwin 17.5.0
17 verbose argv "/usr/local/Cellar/node/9.3.0_1/bin/node" "/usr/local/bin/npm" "run" "run-all"
18 verbose node v9.3.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error multi-gekko@1.0.0 run-all: `npm-run-all --parallel BCH-MACD.gda ETH-MACD.gda ADA-RSI.bin BCH-RSI.gda ETH-RSI.bin`
22 error Exit status 1
23 error Failed at the multi-gekko@1.0.0 run-all script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

`

**Comment by bettimms** [comment]
I'm not spotting anything that leads to a solution but I'll give few suggestions! First I hope you changed `util.js` with the one inside multi-gekko?!

Try:
- Delete configs folder and run generate again
- Try to run one of the pairs alone like for example `npm run BCH-MACD.gda` instead of `npm run run-all`
- If that doesn't work, go to gekko and try to run gekko as you'd do normally suggested by gekko, to try find from where the problem is coming

I hope any of the points helps
