### ISSUE TITLE
I have an error please help me @bettimms

### ISSUE THREAD

**Issue by alexnguyen2018** [bettimms/multi-gekko#5]
Error: Cannot find module 'C:\multi-gekko\UsersAdministratorDownloadsgekko-devel
opgekko-develop'
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Function.Module.runMain (module.js:693:10)
at startup (bootstrap_node.js:191:16)
at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multi-gekko@1.0.0 ETH-NNv2.gda: node C:UsersAdministratorDownloadsgekk o-developgekko-develop --config C:\multi-gekko/configs/ETH/ETH-NNv2.gda.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the multi-gekko@1.0.0 ETH-NNv2.gda script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Administrator\AppData\Roaming\npm-cache_logs\2018-07-01T0
3_12_49_782Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multi-gekko@1.0.0 BCC-StepGains.bin: node C:UsersAdministratorDownload sgekko-developgekko-develop --config C:\multi-gekko/configs/BCC/BCC-StepGains.bi n.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the multi-gekko@1.0.0 BCC-StepGains.bin script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Administrator\AppData\Roaming\npm-cache_logs\2018-07-01T0
3_12_49_812Z-debug.log
module.js:549
throw err;
^

Error: Cannot find module 'C:\multi-gekko\UsersAdministratorDownloadsgekko-devel
opgekko-develop'
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Function.Module.runMain (module.js:693:10)
at startup (bootstrap_node.js:191:16)
at bootstrap_node.js:612:3
module.js:549
throw err;
^

**Comment by bettimms** [comment]
Im really sorry for late reply. Have been in a long vacation and then forgot about it! I think you've issue with the path as far as I can see. Will close it hoping that you already resolved it!
